
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import localFont from 'next/font/local';

const fordAntenna = localFont({
  src: [
    {
      path: "../../public/fonts/FordAntenna-Thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../public/fonts/FordAntenna-ExtraLight.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/fonts/FordAntenna-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/FordAntenna-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/FordAntenna-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/FordAntenna-Black.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-fordAntenna",
  preload: true,
  display: "swap",
});

export const metadata = {
  title: "Ford",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fordAntenna.variable} `}>
        <Header />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
