import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import ToasterWrapper from "@/components/common/ToasterWrapper";
import localFont from "next/font/local";

export const metadata = {
  title: "Ford",
  description: "Generated by create next app",
};

export const fordf1 = localFont({
  src: [
    {
      path: "../../../public/fonts/FordF-1-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../../public/fonts/FordF-1-Semibold.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../../public/fonts/FordF-1-Bold.woff2",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-fordf1",
  preload: true,
  display: "swap",
});

export const fordAntenna = localFont({
  src: [
    {
      path: "../../../public/fonts/FordAntenna-Light.woff2",
      weight: "300",
      style: "light",
    },
    {
      path: "../../../public/fonts/FordAntenna-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../../public/fonts/FordAntenna-Medium.woff2",
      weight: "500",
      style: "medium",
    },
  ],
  variable: "--font-antenna",
  preload: true,
  display: "swap",
});

// const barlow = Barlow({
//   subsets: ["latin"],
//   weight: ["100", "200", "300", "400", "600", "700", "800", "900"],
//   display: "swap",
// });

async function getHeaderData() {
  try {
    console.log("Fetching header data (server-side)");

    const res = await fetch(
      `${process.env.NEXT_PUBLIC_API_URL}/wp-json/ford/v1/header`,
      {
        cache: "no-store", // No caching, always fetch fresh
      }
    );

    if (!res.ok) {
      throw new Error("Failed to fetch header data");
    }

    const data = await res.json();
    return data?.header_acf || null;
  } catch (error) {
    console.error("Header fetch failed:", error);
    return null;
  }
}

async function getFooterData() {
  try {
    console.log("Fetching footer data (server-side)");

    const res = await fetch(
      `${process.env.NEXT_PUBLIC_API_URL}/wp-json/ford/v1/footer`,
      {
        cache: "no-store",
      }
    );

    if (!res.ok) {
      throw new Error("Failed to fetch footer data");
    }

    const data = await res.json();
    return data?.footer_acf || null;
  } catch (err) {
    console.error("Footer fetch failed", err);
    return null;
  }
}

export default async function RootLayout({ children }) {
  const [headerData, footerData] = await Promise.all([
    getHeaderData(),
    getFooterData(),
  ]);

  return (
    <html lang="en">
      <body className={`${fordf1.variable} ${fordAntenna.variable}`}>
        <Header data={headerData} />
        <main className="flex-grow">
          {children}
          <ToasterWrapper />
        </main>
        <Footer data={footerData} />
      </body>
    </html>
  );
}
