import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { Barlow } from "next/font/google";
import localFont from "next/font/local";

export const metadata = {
  title: "Ford",
  description: "Generated by create next app",
};

export const fordAntenna = localFont({
  src: [
    {
      path: "../../../public/fonts/StretchProRegular.woff2",
      weight: "100",
      style: "normal",
    },
  ],
  variable: "--font-fordAntenna",
  preload: true,
  display: "swap",
});

const barlow = Barlow({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "600", "700", "800", "900"],
  display: "swap",
});

async function getHeaderData() {
  try {
    console.log("Fetching header data (server-side)");

    const res = await fetch(
      `${process.env.NEXT_PUBLIC_API_URL}/wp-json/ford/v1/header`,
      {
        cache: "no-store", // No caching, always fetch fresh
      }
    );

    if (!res.ok) {
      throw new Error("Failed to fetch header data");
    }

    const data = await res.json();
    return data?.header_acf || null;
  } catch (error) {
    console.error("Header fetch failed:", error);
    return null;
  }
}

async function getFooterData() {
  try {
    console.log("Fetching footer data (server-side)");

    const res = await fetch(
      `${process.env.NEXT_PUBLIC_API_URL}/wp-json/ford/v1/footer`,
      {
        // This ensures fresh data every render (no cache)
        cache: "no-store",
      }
    );

    if (!res.ok) {
      throw new Error("Failed to fetch footer data");
    }

    const data = await res.json();
    return data?.footer_acf || null;
  } catch (err) {
    console.error("Footer fetch failed", err);
    return null;
  }
}

export default async function RootLayout({ children }) {
  const [headerData, footerData] = await Promise.all([
    getHeaderData(),
    getFooterData(),
  ]);

  return (
    <html lang="en">
      <body className={`${barlow.className} ${fordAntenna.variable}`}>
        <Header data={headerData} />
        <main className="flex-grow">{children}</main>
        <Footer data={footerData} />
      </body>
    </html>
  );
}
